### ISSUE TITLE
运行过程中出现问题

### ISSUE THREAD

**Issue by wangguangzhong** [Ezoio/jigsaw#3]
您好 ，在运行过程中出现如下错误
thirdScriptError 
 sdk uncaught third Error 
 hashCode is not defined 
 ReferenceError: hashCode is not defined
    at http://127.0.0.1:17048/appservice/utils/util.js:131:13
    at require (WAService.js:1:1297709)
    at WAService.js:1:1297319
    at http://127.0.0.1:17048/appservice/pages/person/person.js:5:13
    at require (WAService.js:1:1297709)
    at <anonymous>:14:7
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:17048/appservice/appservice?t=1565313281719:1156:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:17048/appservice/appservice?t=1565313281719:1168:20)
求帮忙解决

**Comment by SSSDNSY** [comment]
你好，可以把我们util.js的导出
`module.exports = {
  sleep: sleep,
  isEmpty: isEmpty,
  updateScore: updateScore,
  getScore:getScore,
  music: music
}`
里面的hashCode 删除掉哦，因为目前由我一个人维护jigsaw，这个github的文件可能不是最新的。

_感谢你对jigsaw的关注，更多相关问题可以加我QQ_：**736259020**

**Comment by wangguangzhong** [comment]
非常感谢

**Comment by wangguangzhong** [comment]
您好 ，还有一点小问题
VM256:5 tabBar.list[0].iconPath 文件不存在
tabBar.list[0].selectedIconPath 文件不存在
tabBar.list[1].iconPath 文件不存在
tabBar.list[1].selectedIconPath 文件不存在
这些图片好像没有上传
